---
spring:
  application:
    name: ex

  datasource:
    url: jdbc:mysql://localhost:3306/productDB
    username: mysql
    password: changemeinprod!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret: 6Rk8dVjG0tM1FZT7nLqXztdVd7y9hTqY3FjXZ3qH1Nc=
    expiration: 3600000

encryption:
  secret:
    key: "s8Hd#29pQmF@l3Kv"